idim: 768
hidden_dim: 256

accum_grad: 4
nepochs: 40
nworkers: 2
log_interval: 100
five_fold: True
batch_size: 1
batch_bins: 6000000
#mcc: True

train_json: "inputdata/sample.json"

lr: 1e-3

# - I don't know what the hell is going on but if
# - you specify the batch_enable in config file, 
# - even you set it as False, parser still recognize 
# - it as true...