# - basic setup
idim: 768
hidden_dim: 256
lr: 1e-4
accum_grad: 4
nepochs: 20
nworkers: 2
log_interval: 100
batch_size: 1
five_fold: True
train_json: "inputdata/sample.json"

# - MFCC
mcc: True
transfer_loss_factor: 10